name: Generate markdown and static html

on:
  workflow_dispatch:
  issues:
    types: [opened, edited, deleted, labeled, milestoned]
  push:
    branches:
      - master
    paths:
      - main.py

jobs:
  readme:
    name: Generate markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Configure pip cache
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: venv
          key: pip-1-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Generate new md
        if: |
          github.event_name == 'workflow_dispatch' || 
          github.event_name == 'push' || 
          github.event.issue.user.login == github.repository_owner
        run: |
          source venv/bin/activate
          python main.py ${{ secrets.G_T }} ${{ github.repository }}
          dir_name="docs"
          if [ ! -d "$dir_name" ]; then
            mkdir $dir_name
            echo "Directory $dir_name created."
          else
            echo "Directory $dir_name already exists."
          fi

      - name: convert md to html
        uses: docker://pandoc/latex:2.9
        with:
          entrypoint: /bin/sh
          args: -c "pandoc ./record.md -o docs/index.html;"

      - name: Push doc
        run: |
          git config --local user.email "${{ vars.GIT_EMAIL }}"
          git config --local user.name "${{ vars.GIT_NAME }}"
          git add record.md docs/*
          git commit -a -m '[auto]update record and static html' || echo "nothing to commit"
          git push || echo "nothing to push"
